// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToPeer(arg1) {
  return window['go']['main']['App']['ConnectToPeer'](arg1);
}

export function GetConnectedPeers() {
  return window['go']['main']['App']['GetConnectedPeers']();
}

export function GetDiscoveredPeers() {
  return window['go']['main']['App']['GetDiscoveredPeers']();
}

export function GetFileStats(arg1) {
  return window['go']['main']['App']['GetFileStats'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitiateFileTransfer(arg1, arg2) {
  return window['go']['main']['App']['InitiateFileTransfer'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RespondToPeerConnectionRequest(arg1, arg2) {
  return window['go']['main']['App']['RespondToPeerConnectionRequest'](arg1, arg2);
}

export function StartPeerDiscovery() {
  return window['go']['main']['App']['StartPeerDiscovery']();
}

export function StopPeerDiscovery() {
  return window['go']['main']['App']['StopPeerDiscovery']();
}
