// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {peerdiscovery} from '../models';
import {main} from '../models';

export function CalculateFileHash(arg1:string):Promise<string>;

export function ConnectToPeer(arg1:peerdiscovery.DiscoveredPeer):Promise<void>;

export function GetConnectedPeers():Promise<Array<peerdiscovery.DiscoveredPeer>>;

export function GetDiscoveredPeers():Promise<Array<peerdiscovery.DiscoveredPeer>>;

export function GetFileStats(arg1:Array<string>):Promise<Array<main.SelectedItem>>;

export function Greet(arg1:string):Promise<string>;

export function InitiateFileTransfer(arg1:string,arg2:Array<main.SelectedItem>):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<Array<string>>;

export function RespondToPeerConnectionRequest(arg1:string,arg2:boolean):Promise<void>;

export function StartPeerDiscovery():Promise<void>;

export function StopPeerDiscovery():Promise<void>;
